name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    environment: Deploy
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 1.21
      - name: Maven Package
        run: mvn -B clean package -DskipTests

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: |
            target/*.jar
            pom.xml
          retention-days: 1

  unit-test:
    runs-on: ubuntu-latest
    environment: Deploy
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: Package
          path: ./
      - name: set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 1.21
      - name: Maven Test
        run: mvn -B test

  docker-build-publish:
      runs-on: ubuntu-latest
      environment: Deploy
      needs: [unit-test]
      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
        with:
          name: Package
          path: ./

      - name: Build image
        run: docker build -t person_service . --tag antonidass/rsoi:latest

      - name: Publish Docker image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
        run: |
          echo "${DOCKERHUB_PASS}" | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin
          docker push antonidass/rsoi:latest

      # - name: install ssh keys
      #   run: |
      #     install -m 600 -D /dev/null ~/.ssh/id_rsa
      #     echo "${{ secrets.ID_RSA }}" > ~/.ssh/id_rsa
      #     ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} > ~/.ssh/known_hosts

      # - name: Deploy
      #   env:
      #     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      #     DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
      #   run: ssh ${{ secrets.DEPLOY_USR }}@${{ secrets.DEPLOY_HOST }} "echo "${DOCKERHUB_PASS}" | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin && docker pull antonidass/rsoi:latest && cd /opt && docker-compose up -d --force-recreate"

  deploy:
    name: Deploy service on VM
    environment: Deploy
    runs-on: ubuntu-latest
    needs: [ docker-build-publish ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Move to VM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USR }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "docker-compose.yml"
          target: /opt

#      - name: Run API Tests
#        uses: matt-ball/newman-action@master
#        with:
#          collection: postman/[inst] Lab1.postman_collection.json
#          environment: postman/[inst][heroku] Lab1.postman_environment.json
#          delayRequest: 100
#          reporters: '[ "cli" ]'
#
#      - name: Autograding
#        uses: education/autograding@v1
#        continue-on-error: true
#
#      - name: Github auto grader mark
#        uses: Romanow/google-sheet-autograder-marker@v1.0
#        with:
#          google_token: ${{secrets.GOOGLE_API_KEY}}
#          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
#          homework_number: 1
#          user_column: "D"
#          column_offset: "F"
#          mark: "'+"
